spring:
  application:
    name: Communication-Service
  data:
    mongodb:
      uri: ${MONGO_URI}

server:
  port: 8080
  error:
    include-message: always

communication:
  sendgrid:
    url: https://api.sendgrid.com/v3/mail/send
    api-key: ${SENDGRID_API_KEY}
    read-timeout: 5000
    connect-timeout: 3000
    senders:
      trentonrush: me@trentonrush.com
    recipients: # set specific recipients for a template
      personal: ${CONTACT_EMAIL_GROUP}
    templates:
      personal: d-81b2bcc6f4804868878e3c3bd0a64080
  twilio:
    account-sid: ${TWILIO_SID}
    messaging-service-sid: ${TWILIO_MESSAGING_SERVICE_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}
    senders:
      trentonrush: +12345678910
    templates: # Content SIDs
      personal: HX7139cf7ff4239e7f96604f3baba49498

  openAi:
    url: "https://api.openai.com/v1/chat/completions"
    api-key: ${OPENAI_API_KEY}
    read-timeout: 5000
    connect-timeout: 3000

okta:
  oauth2:
    issuer: ${AUTH_ISSUER}
    audience: ${AUTH_AUDIENCE}
