name: Deploy to DigitalOcean

on:
  push:
    branches: [ "feature/add-deploy-script" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ vars.SERVICE_NAME }}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --build-arg DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} -t $DOCKER_IMAGE .

      - name: Save Docker image to a file
        run: |
          docker save $DOCKER_IMAGE | gzip > ${{ vars.SERVICE_NAME }}.tar.gz

      - name: Copy Docker image to DigitalOcean Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ vars.SERVICE_NAME }}.tar.gz
          target: /home/${{ secrets.DO_DROPLET_USERNAME }}/${{ vars.SERVICE_NAME }}

      - name: SSH and Load Docker image on DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            gunzip /home/${{ secrets.DO_DROPLET_USERNAME }}/${{ vars.SERVICE_NAME }}/${{ vars.SERVICE_NAME }}.tar.gz
            docker load -i /home/${{ secrets.DO_DROPLET_USERNAME }}/${{ vars.SERVICE_NAME }}/${{ vars.SERVICE_NAME }}.tar
            docker stop ${{ vars.SERVICE_NAME }} || true
            docker rm ${{ vars.SERVICE_NAME }} || true
            docker run -d --name ${{ vars.SERVICE_NAME }} -p 80:8080 $DOCKER_IMAGE