name: Deploy to DigitalOcean

on:
  push:
    branches: [ "feature/add-deploy-script" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t communication-service:latest .

      - name: Save Docker image to a file
        run: |
          docker save communication-service:latest | gzip > communication-service.tar.gz

      - name: Copy Docker image to DigitalOcean Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: communication-service.tar.gz
          target: /${{ secrets.DO_DROPLET_USERNAME }}/communication-service.gz

      - name: SSH and Load Docker image on DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            gunzip /${{ secrets.DO_DROPLET_USERNAME }}/communication-service.tar.gz
            docker load -i /${{ secrets.DO_DROPLET_USERNAME }}/communication-service.tar
            docker stop communication-service || true
            docker rm communication-service || true
            docker run -d --name communication-service -p 80:8080 communication-service:latest